name: Kashyap Tumkur
description: Hello! 
meta_description: "Kashyap's personal blog."

aboutPage: true

highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://kashyaptumkur.com'
google_analytics: 'UA-77423805-1'
disqus: true
disqus_shortname: 'nonlogic'

# Details for the RSS feed generator
url:            'http://kashyaptumkur.com'
author:         'Kashyap Tumkur'
authorTwitter:  'nonlogic'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
