permalink: /:categories/:title.html
url: "http://kashyaptumkur.com"
full_name: "Kashyap Tumkur"
first_name: "Kashyap"
last_name: "Tumkur"
blog_title: "Kashyap's Blog"
author_img_name_path: "/images/users/bio-photo.jpg"
disqus_shortname: "nonlogic"
copyright_year: "2016"
google_analytics_code: "UA-77423805-1"
aboutme: "Better than I was yesterday."
twitter: "nonlogic"
github: "nonlogic"
facebook: ""
linkined_url: "http://www.linkedin.com/in/KashyapTumkur"
